
<?php

   include("docx_generator.php");

   /**
    * Implements hook_permission().
    */
   function main_menu_handler_permission(){

      $permissions = array();

      $permissions['my account access'] = array(
         'title' => t("Access to My Account Link"),
         'description' => t("Access to my account link.")
      );

      $permissions['report form access'] = array(
         'title' => t("Access to Report Form Link"),
         'description' => t("Access to report form link.")
      );

      return($permissions);
   }

   /**
    * Implements hook_menu().
    */
   function main_menu_handler_menu(){

      $items = array();

      $items['report_form'] = array(
         'title' => 'Informe',
         'description' => 'Solicitud de Informe de Inteligencia Competitiva.',
         'type' => MENU_NORMAL_ITEM,
         'page callback' => 'drupal_get_form',
         'page arguments' => array('main_menu_handler_form'),
         'access arguments' => array('report form access')
      );

      $items['my_account'] = array(
         'title' => 'Mi Cuenta',
         'type' => MENU_NORMAL_ITEM,
         'page callback' => 'main_menu_handler_redirect',
         'access arguments' => array('my account access')
      );

      return($items);
   }

   /**
    * Using drupal_goto() function to redirect user to "/user" path.
    */
   function main_menu_handler_redirect(){
      drupal_goto('user');
   }

   /**
    * Implements hook_form().
    */
   function main_menu_handler_form($form, &$form_state) {

      $form = array();

      $form['field_empresa'] = array(
         '#type' => 'textfield',
         '#title' => 'Empresa',
         //'#description' => 'Ingrese el nombre de la empresa.',
         '#placeholder' => t('Nombre de la empresa'),
         '#required' => FALSE
      );

      $form['dropdown_actividadEconomica'] = array(
         '#title' => t('Actividad Económica'),
         '#type' => 'select',
         //'#description' => 'Seleccione la actividad econónica de la empresa.',
         '#options' => array(
            t('one'),
            t('two'),
            t('three')
         ),
         '#required' => FALSE
      );

      $form['dropdown_sectorProductivo'] = array(
         '#title' => t('Sector Productivo'),
         '#type' => 'select',
         //'#description' => 'Seleccione el sector productivo donde se desempeña la empresa.',
         '#options' => array(
            t('one'),
            t('two'),
            t('three')
         ),
         '#required' => FALSE
      );

      $form['dropdown_tecnologiaPrincipal'] = array(
         '#title' => t('Tecnologia Principal'),
         '#type' => 'select',
         //'#description' => 'Seleccione la principal tecnología empleada por la ' .
            //'empresa para la prestación de su servicio o fabricación de su producto.',
         '#options' => array(
            t('one'),
            t('two'),
            t('three')
         ),
         '#required' => FALSE
      );

      $form['dropdown_serviciosYProductos'] = array(
         '#title' => t('Servicios y Productos Principales'),
         '#type' => 'select',
         //'#description' => 'Seleccione el principal producto o servicio que comercializa la empresa.',
         '#options' => array(
            t('one'),
            t('two'),
            t('three')
         ),
         '#required' => FALSE
      );

      $countryOptions = main_menu_handler_get_country_options();
      if(isset($form_state['values']['dropdown_paisEmpresa'])){
         $countrySelected =  $form_state['values']['dropdown_paisEmpresa'];
      }else{
         $countrySelected = key($countryOptions);
      }

      $form['dropdown_paisEmpresa'] = array(
         '#title' => t('País'),
         '#type' => 'select',
         '#options' => $countryOptions,
         '#default_value' => $countrySelected,
         '#required' => FALSE,
         '#ajax' => array(
            'event' => 'change',
            'callback' => 'main_menu_handler_country_dropdown_callback',
            'wrapper' => 'state-dropdown-replace',
            'method' => 'replace'
         )
      );

      $stateOptions = main_menu_handler_get_state_options($countrySelected);
      if(isset($form_state['values']['dropdown_estadoEmpresa'])){
         $stateSelected =  $form_state['values']['dropdown_estadoEmpresa'];
      }else{
         $stateSelected = key($stateOptions);
      }

      $form['dropdown_estadoEmpresa'] = array(
         '#title' => t('Estado/Provincia'),
         '#type' => 'select',
         '#options' => $stateOptions,
         '#default_value' => $stateSelected,
         '#required' => FALSE,
         '#prefix' => '<div id="state-dropdown-replace" class="form-item form-type-select form-group">',
         '#suffix' => '</div>',
         '#ajax' => array(
            'event' => 'change',
            'callback' => 'main_menu_handler_state_dropdown_callback',
            'wrapper' => 'city-dropdown-replace',
            'method' => 'replace'
         )
      );

      $cityOptions = main_menu_handler_get_city_options($stateSelected);
      if(isset($form_state['values']['dropdown_cityEmpresa'])){
         $citySelected =  $form_state['values']['dropdown_cityEmpresa'];
      }else{
         $citySelected = key($cityOptions);
      }

      $form['dropdown_ciudadEmpresa'] = array(
         '#title' => t('Ciudad'),
         '#type' => 'select',
         '#required' => FALSE,
         '#prefix' => '<div id="city-dropdown-replace" class="form-item form-type-select form-group">',
         '#suffix' => '</div>',
         '#options' => $cityOptions,
         '#default_value' => $citySelected
      );

      $form['submit_button'] = array(
         '#type' => 'submit',
         '#value' => t('Solicitar')
      );

      return($form);
   }

   function main_menu_handler_form_validate($form, &$form_state){

   }

   function main_menu_handler_form_submit($form, &$form_state){

   }

   function main_menu_handler_country_dropdown_callback($form, &$form_state) {
      return $form['dropdown_estadoEmpresa'];
   }

   function main_menu_handler_state_dropdown_callback($form, &$form_state) {
      return $form['dropdown_ciudadEmpresa'];
   }

   function main_menu_handler_get_country_options(){
      try{
         $countryQueryResult = db_query("SELECT countryid, country FROM c_a_drupal_country ORDER BY country ASC");
         $countryArray = array();
         $countryArray[0] = '-- Seleccionar País --';
         foreach($countryQueryResult as $row){
            $countryArray[$row->countryid] = $row->country;
         }
      }catch(Exception $e){
         echo($e->getMessage());
      }
      return $countryArray;
   }

   function main_menu_handler_get_state_options($key = ''){
      try{
         $countryId = $key;
         $stateQueryResult = db_query(
            "SELECT id, statename FROM c_a_drupal_state WHERE countryid = :countryid",
            array(':countryid' => $countryId)
         );
         $stateArray = array();
         $stateArray[0] = '-- Seleccionar Estado o Provincia --';
         foreach($stateQueryResult as $row){
            $stateArray[$row->id] = $row->statename;
         }
      }catch(Exception $e){
         echo($e->getMessage());
      }
      return($stateArray);
   }

   function main_menu_handler_get_city_options($key = ''){
      try{
         $stateId = $key;
         $cityQueryResult = db_query(
            "SELECT id, city FROM c_a_drupal_city WHERE stateid = :stateid",
            array(':stateid' => $stateId)
         );
         $cityArray = array();
         $cityArray[0] = '-- Seleccionar Ciudad --';
         foreach($cityQueryResult as $row){
            $cityArray[$row->id] = $row->city;
         }
      }catch(Exception $e){
         echo($e->getMessage());
      }
      return($cityArray);
   }

